// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmxGQ_lvF69V0JLTIkWf7Hzx2OP7--aHQ',
    appId: '1:341616675567:web:c512517953a69c5dcea91a',
    messagingSenderId: '341616675567',
    projectId: 'visit-rwanda16',
    authDomain: 'visit-rwanda16.firebaseapp.com',
    storageBucket: 'visit-rwanda16.appspot.com',
    measurementId: 'G-6FCM85QNNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLQ1ZAY1Z3n3rsiVuS3gugSIswAfLGH-Y',
    appId: '1:341616675567:android:25714f809ccbe366cea91a',
    messagingSenderId: '341616675567',
    projectId: 'visit-rwanda16',
    storageBucket: 'visit-rwanda16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmvIqWpkbf70BTg-Mw3bqeWj2Pd53rV7k',
    appId: '1:341616675567:ios:eacf74e9c4daf6b5cea91a',
    messagingSenderId: '341616675567',
    projectId: 'visit-rwanda16',
    storageBucket: 'visit-rwanda16.appspot.com',
    iosBundleId: 'com.example.visitRwanda',
  );
}
